### ISSUE TITLE
Change data type of state

### ISSUE THREAD

**Issue by frehe** [SensorsINI/CartPoleSimulation#4]
Currently: Cart state is a namespace with angle, angleD, angleDD, position, positionD, positionDD

Decision Marcin & Frederik: Convert state representation to numpy array throughout the repo. Advantage: Performance gains for mppi parallelization and RNN computations. Disadvantage: Order of variables must be clearly documented.

The following variables are saved in the state array in alphabetical order: angle, angle.cos, angle.sin, angleD, angleDD, position, positionD, positionDD. The order will be documented in code.

**Comment by marcinpaluch1994** [comment]
I would just put angle.cos, angle.sin before angleD as np.sort() puts '.' before 'D'.

**Comment by frehe** [comment]
Merged related pull requests.
